### ISSUE TITLE
Message d'erreur !

### ISSUE THREAD

**Issue by Darkicross** [HikeGame/Royal-War#1]
bonjour,

Lorsque que l'on mets le serveur en mode maintenance (univers fermer) et qu'une personne essaye de se login ou bien de s'inscrire cela marque:

NOTICE
Message: Undefined index: PLANETS
File: /includes/pages/game/AbstractGamePage.class.php
Line: 105
URL: http://ogame.the-repended.net/uni2/game.php
PHP-Version: 5.6.30
PHP-API: litespeed
MySQL-Client-Version: 10.0.30-MariaDB
2Moons Version: 1.8.git
Debug Backtrace:
#0 /includes/pages/game/AbstractGamePage.class.php(105): errorHandler(8, 'Undefined index...', 'FILEPATH ...', 105, Array)
#1 /includes/pages/game/AbstractGamePage.class.php(164): AbstractGamePage->getNavigationData()
#2 /includes/pages/game/AbstractGamePage.class.php(234): AbstractGamePage->getPageData()
#3 /includes/pages/game/AbstractGamePage.class.php(215): AbstractGamePage->display('error.default.t...')
#4 /includes/pages/game/ShowErrorPage.class.php(34): AbstractGamePage->printMessage('Le jeu est actu...', false, NULL)
#5 /includes/common.php(168): ShowErrorPage::printError('Le jeu est actu...', false)
#6 /game.php(24): require('FILEPATH ...')
#7 {main}

Merci de votre patiente

**Comment by HikeGame** [comment]
Merci pour cette information il sera mis en place pour ça correction.

**Comment by HikeGame** [comment]
Correction effectuer je ferme donc cette issues
